#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
v4: 在 v3 基础上补搜实习岗
- 保留 v3 的 42 份 JD
- 新增 30+ 份专门补搜的实习岗（AI 大模型方向）
- 重点来源: 牛客网 / BOSS 直聘 / 官方公众号 / 北大未名 BBS / 实习僧 / 知乎

幂等说明 (2026-06-26 R3-I 收尾修订):
- v1/v2/v3 历史版本已 trash（见 AGENTS.md）
- 脚本现在**从 v4 文件自包含读取** (DST = SRC), 不再依赖已删除的 v3
- 再跑只会得到 0 个 new_jds (NEW_JDS 里的 ID 全部已在 v4 里), 写回相同内容
- 如果将来要把 NEW_JDS 扩到 v5, 直接在列表末尾追加新 JD 即可
"""
import json
from pathlib import Path

# v4 文件自包含: 脚本从 v4 读取, 再跑是幂等操作
SRC = Path(r"D:\简历帮\AI岗位JD库_v4_intern.json")
DST = Path(r"D:\简历帮\AI岗位JD库_v4_intern.json")

# ============= 新增 JD（按 id 排序）=============
# 字段: id, company, role_category, job_type, title, salary_range, location, source_url, source_quality, full_text
# scores 字段手工给分, 因为我们没原始 3 维度打分逻辑, 但保留框架
# 注: 这些都是专门补搜的实习岗, 主要用于扩充 intern_match = strong 的池子

NEW_JDS = [
    # ========== 阿里巴巴（实习岗 6 条新增）==========
    {
        "id": "JD-A007",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "阿里通义实验室 LLM 研究实习生（AI Search 方向）",
        "salary_range": "未披露",
        "location": "北京 / 杭州 / 上海",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "团队：阿里巴巴通义实验室 LLM 研究团队\n\n研究项目主要面向 AI Search 方向的研究，具体工作包括基于文本检索、多模态搜索、检索增强，大模型 CPT、SFT、RewardModel 等工作\n\n职位亮点：\n1. 深度参与最前沿的预训练语言模型相关研究\n2. 与行业内顶尖人才共事，快速成长\n3. 参与国际顶级会议论文撰写与发表\n4. 充足的 GPU 计算资源\n5. 有校招转正机会\n\n任职要求：\n1. 熟练使用 PyTorch 框架进行深度学习模型训练与优化\n2. 拥有扎实的编程基础和出色的工程实现能力\n3. 在相关领域（自然语言处理、信息检索、预训练大模型）有顶会论文（ACL/EMNLP/ICLR/NeurIPS/ICML 等）发表者优先\n4. 实习时间不少于 6 个月",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "牛客网 2025-2026 当季实习专页",
            "quality": 38,
            "quality_reason": "职责 5 项亮点 + 任职要求 4 项 + 字段完整",
            "authenticity": 28,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 94,
            "grade": "A",
        },
    },
    {
        "id": "JD-A008",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "阿里通义对话智能团队 大模型研究实习生（多模态 Character/RL/Agent）",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://blog.csdn.net/c9yv2cf9i06k2a9e/article/details/146330416",
        "source_quality": "trusted",
        "full_text": "团队：阿里通义实验室对话智能团队，过去三年发表 60+ 篇国际顶会论文，业务场景包括通义晓蜜、通义星辰、通义灵码\n\n岗位职责：\n1. 多模态 Character 模型的算法研究，探索多模态表征学习与对齐技术\n2. Agentic Reinforcement Learning：研究具备自主决策与持续优化能力的大模型强化学习范式\n3. 可控与可信 AI Agent：研究具备指令跟随、风格与内容可控、安全可靠的通用智能体\n\n任职要求：\n1. 在读博士生，专注于机器学习、AI、智能控制等相关领域\n2. 在深度学习、强化学习、多智能体等领域有深入的研究经验\n3. 在相关研究领域的顶级期刊和会议上发表过论文，至少有一篇一作 CCF-A 级论文\n4. 熟练使用 pytorch/tensorflow 等至少一种主流深度学习框架\n5. 实习岗，wk258730@alibaba-inc.com",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "CSDN 转载内推帖，2026 春实习",
            "quality": 42,
            "quality_reason": "职责 3 项 + 任职要求 5 项 + 业务场景具体",
            "authenticity": 22,
            "authenticity_reason": "CSDN 转载（可信，有内推邮箱）",
            "total": 86,
            "grade": "A",
        },
    },
    {
        "id": "JD-A009",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "阿里通义实验室 研发实习生（推理/CV/NLP/多模态/ModelScope）",
        "salary_range": "未披露",
        "location": "北京 / 杭州",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "团队：阿里巴巴通义实验室研发团队\n\n岗位职责：\n1. 参与大模型推理框架以及定制微调技术的研发与优化\n2. 建设支持高并发访问的弹性平台服务后端，推动大模型在实际业务中的落地\n3. 参与自然语言处理、计算机视觉、语音、多模态模型的研发\n4. 建设中国最具影响力的 AI 模型开源社区（ModelScope）\n5. 分析和处理大规模图计算相关问题，研发高性能图计算系统\n\n任职要求：\n1. 计算机科学或相关专业硕士及以上学历\n2. 具备良好的编程能力和代码风格，有分布式系统开发经验者优先\n3. 加分项：ACM/ICPC 等知名编程竞赛获奖、HuggingFace/ModelScope 平台经验、分布式计算经验",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 40,
            "quality_reason": "职责 5 项 + 任职要求 3 项",
            "authenticity": 28,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 96,
            "grade": "A",
        },
    },
    {
        "id": "JD-A010",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "阿里通义实验室 多模态大模型与智能体研究实习生",
        "salary_range": "未披露",
        "location": "北京 / 杭州",
        "source_url": "https://bbs.pku.edu.cn/v2/mobile/post-read.php?bid=896&threadid=18965892",
        "source_quality": "trusted",
        "full_text": "团队：阿里通义实验室\n\n岗位职责：\n1. 探索研究多模态理解大模型的设计与开发，包括生成理解统一、多模态理解、强化学习/RLHF 后训练\n2. 参与研发多模态理解大模型开发等下一代人工智能核心技术\n3. 主要方向为多模态大模型与 GUI Agent\n4. 日常实习，以 project 和 paper 工作为主\n\n任职要求：\n1. 计算机科学、人工智能、机器学习或相关领域的硕士或博士在读\n2. 在自回归模型、多模态生成理解、计算机视觉、NLP、机器学习等一个或多个领域有较深入的研究\n3. 加分项：在 CVPR/ECCV/ICCV/NeurIPS/ICLR/ICML/SIGGRAPH 等顶会发表论文、ACM/ICPC 获奖、多模态/大模型/基础模型项目\n4. 工作地点北京/杭州，zjn271703@alibaba-inc.com",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "北大 BBS 实习帖",
            "quality": 38,
            "quality_reason": "职责 4 项 + 任职要求 3 项",
            "authenticity": 24,
            "authenticity_reason": "北大 BBS + 阿里邮箱一手投递",
            "total": 84,
            "grade": "A",
        },
    },
    {
        "id": "JD-A011",
        "company": "阿里巴巴",
        "role_category": "data_annot",
        "job_type": "ai_pm",
        "title": "阿里智能信息 大模型 AI 数据工程实习生（夸克/UC）",
        "salary_range": "未披露",
        "location": "北京 / 杭州",
        "source_url": "https://www.163.com/dy/article/JM7PLH9G0514CESC.html",
        "source_quality": "trusted",
        "full_text": "团队：阿里智能信息事业群（夸克 App、UC 浏览器、书旗小说、超级汇川）\n\n岗位：大模型 AI 数据工程实习生\n\n我们希望你是：\n1. 不限专业、不限毕业时间，只要你对 AI 充满兴趣，那就有机会加入我们！\n2. 对 AGI 时代充满热情，积极看待变化、差距，对未知的可能性充满信心\n3. 具备较好的表达能力，对复杂任务的统筹和优化能力\n4. 对大模型有基本了解，有产品设计、交互界面设计或数据标注经验者优先\n5. 具备充足的实习时间，每周到岗 4 天及以上\n\n收获：\n1. 全球顶级 AI 专家指导，直接参与业内领先大模型的构建\n2. 深度业务场景参与，为亿级用户提供智能服务\n3. 通过深入理解数据与模型的交互，提升跨学科思维能力\n4. 校招转正直通卡\n\n投递链接：https://talent.quark.cn/campus/qrcode/home",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "Hi 实习 2026 春招专页",
            "quality": 32,
            "quality_reason": "资格要求 5 项 + 收获 4 项",
            "authenticity": 22,
            "authenticity_reason": "网易订阅转载 + 官方校招官网投递",
            "total": 76,
            "grade": "A",
        },
    },
    {
        "id": "JD-A012",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "阿里巴巴 2027 届实习生招聘（AI 岗占 80%+）",
        "salary_range": "未披露",
        "location": "杭州 / 北京 / 上海 / 成都 / 广州 / 深圳",
        "source_url": "https://new.qq.com/rain/a/20250318A07NQH00",
        "source_quality": "trusted",
        "full_text": "团队：阿里巴巴 2027 届实习生招聘（含阿里云、淘天、阿里国际、通义实验室、平头哥等 16 个业务集团）\n\nAI 岗位占比：AI 相关岗位占比超八成\n新增七大 AI 校招岗位类型：\n1. AI 应用研发工程师\n2. AI 应用算法工程师\n3. AI Agent 优化工程师\n4. Agent Infra 工程师\n5. AI 数据工程师\n6. AI Infra 工程师\n7. AI SRE\n\n招聘规模：\n- 阿里云招聘 2000 人\n- 阿里国际招聘 900 人\n- 通义实验室新增七类 AI 岗位\n\n工作地点：杭州、北京、上海、成都、广州、深圳及新加坡、法兰克福等海外城市\n\n投递通道：campus-talent.alibaba.com",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2025-03-18 蓝鲸新闻发布，面向 2027 届",
            "quality": 42,
            "quality_reason": "招聘规模 + 岗位类型 + 业务集团全列",
            "authenticity": 25,
            "authenticity_reason": "新闻媒体 + 官方校招通道",
            "total": 95,
            "grade": "A",
        },
    },
    # ========== DeepSeek（实习岗 5 条新增）==========
    {
        "id": "JD-D007",
        "company": "DeepSeek",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "DeepSeek AGI 大模型实习生（NLP/多模态/视觉）",
        "salary_range": "500-1000 元/天",
        "location": "北京",
        "source_url": "https://www.zhipin.com/job_detail/c6ef4039892b2b8a1HRz29q7ElBW.html",
        "source_quality": "trusted",
        "full_text": "公司简介：DeepSeek 是探索通用人工智能（AGI）本质的公司。我们相信大模型是科研+工程+组织的优雅艺术。\n\n实习内容：\n1. 大型语言模型、多模态模型研究，包括模型预训练、理论研究、模型评估等\n2. 计算机视觉研究，包括视觉内容生成、开放场景视觉判别模型\n3. 大模型训练数据构建，训练策略迭代和调优\n\n任职要求：\n1. 计算机及相关专业研究生，特别优秀的本科生亦欢迎申请\n2. 具有扎实的编程功底和 DL/ML 基础，熟练掌握 PyTorch\n3. 顶级 AI 会议论文发表经验或开源项目贡献经验者优先\n4. 自然语言处理、计算机视觉、模型压缩和推理优化等领域经验者优先\n\n实习要求：\n- 实习地：北京中关村融科\n- 实习时间 6 个月以上，每周可以现场实习至少 4 个工作日\n\n我们的优势：\n- 顶尖 GPU 集群算力支持\n- 行业顶尖的实习工资和工作环境\n- 实习期间表现优秀者，可直接获得转正名额\n- 非北京地区学生来京实习有租房补助（3000元/月）\n\n投递邮箱：zy.wu@high-flyer.cn",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "BOSS 直聘 + 脉脉一手实习帖",
            "quality": 42,
            "quality_reason": "实习内容 3 项 + 任职要求 4 项 + 福利 4 项",
            "authenticity": 26,
            "authenticity_reason": "BOSS 一手实习帖 + 脉脉转发",
            "total": 96,
            "grade": "A",
        },
    },
    {
        "id": "JD-D004",
        "company": "DeepSeek",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "DeepSeek 多模态理解与生成统一模型方向 算法实习生",
        "salary_range": "未披露",
        "location": "北京海淀",
        "source_url": "https://blog.csdn.net/c9yv2cf9i06k2a9e/article/details/141406799",
        "source_quality": "trusted",
        "full_text": "团队：DeepSeek AI（多模态理解与生成统一模型方向）\n\n岗位职责：\n- 理解 & 生成统一的多模态大模型，做有影响力的工作\n\n岗位要求：\n1. 要求北京线下实习，实习时间须 6 个月以上\n2. 有较强科研和动手能力，有主导推进研究和写作的经历，至少发表过两篇及以上一作顶会论文\n3. （最重要）有以下方向经验者优先：VQ Tokenizer、Multimodal LLM、Diffusion Model\n\n你将得到：\n- 充足的 A100 资源\n- 行业顶尖的实习工资和工作环境（高配 MacBook Pro + 双 4K 显示器 + 升降桌）\n- 保证产出的情况下工作时间灵活自由\n\n合作导师：陈小康，DeepSeek AI 研究员，2024 年博士毕业于北京大学智能学院，代表作 VisionLLM/CAE/Conditional DETR，Google Scholar 引用 3000+",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "CSDN 2024-08 内推帖（持续有效）",
            "quality": 38,
            "quality_reason": "岗位职责 + 任职要求 3 项 + 福利 3 项 + 导师背书",
            "authenticity": 24,
            "authenticity_reason": "CSDN 转载内推帖（具体到导师）",
            "total": 86,
            "grade": "A",
        },
    },
    {
        "id": "JD-D005",
        "company": "DeepSeek",
        "role_category": "data_annot",
        "job_type": "ai_pm",
        "title": "DeepSeek 数据百晓生实习生",
        "salary_range": "500-550 元/天",
        "location": "北京 / 杭州",
        "source_url": "https://bbs.pku.edu.cn/v2/mobile/post-read-single.php?bid=896&postid=27888970",
        "source_quality": "trusted",
        "full_text": "团队：DeepSeek AGI 数据团队\n\n工作内容：\n1. 大模型安全：负责构建 LLM 内容安全的能力，比如回复干预、输入安全、输出安全等多层内容安全机制，保证大模型在单轮、多轮场景下的输出内容合规\n2. 数据集相关：根据数据集的设计需求和用途，为数据集标准环节制定详实、全面、可执行的标准；对数据集阶段性质检，迭代标注标准\n\n我们希望你是：\n- 对大模型有基本的了解，对数据集的优劣和评估方法有自己的认识\n- 涉猎广泛、博闻强识，对各行各业的知识都拥有强烈的兴趣\n- 会写简单 python 代码，擅长创作大模型 Prompt\n- 至少实习 6 个月，每周到岗 4 天及以上\n\n薪酬福利：\n- 工作地点/薪酬：北京，500 元/天，中饭公司提供，晚饭 80 元餐补\n- HR 邮箱：mm.han@high-flyer.cn\n- HR 微信：18895606352\n- 实习生和校招全职都有 hc，实习仅限可以长期留用的同学",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "北大 BBS 一手实习帖",
            "quality": 36,
            "quality_reason": "工作内容 2 项 + 任职要求 4 项 + 薪酬 4 项",
            "authenticity": 28,
            "authenticity_reason": "北大 BBS + HR 邮箱/微信",
            "total": 92,
            "grade": "A",
        },
    },
    {
        "id": "JD-D006",
        "company": "DeepSeek",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "DeepSeek 2026 大规模招聘 33 岗（实习同步开放）",
        "salary_range": "500-1000 元/天（实习）",
        "location": "北京 / 杭州",
        "source_url": "https://new.qq.com/rain/a/20250625A05DFN00",
        "source_quality": "trusted",
        "full_text": "DeepSeek 在社交平台发布大规模招聘信息，覆盖 7 大类共 33 个岗位，工作地点包括北京和杭州，所有岗位均接受实习。\n\n技术端核心岗位：\n- 全栈开发 / 算法（8 个）\n- AI 搜索算法\n- Agent 底层架构（Harness 团队，对标 Anthropic Claude Code）\n- 超算集群\n- 高性能算子\n- 分布式存储\n- 大模型训推框架\n- AI 跨界技术人才（不设专业背景限制）\n\n产品序列：\n- 通用智能体\n- 多领域专业数据（医学/法律/小语种）\n- AI 创作\n- 情感智能\n- AGI 业务管培生\n\n运维板块：\n- AI 算力集群\n- IDC 机房（覆盖北京、杭州、内蒙古乌兰察布）\n- IT 基础设施\n\nDeepSeek 用人原则：让新人直接承担最核心、最重要的任务。\n\n福利：实习生日薪最高 1000 元，转正 14 薪，年薪百万级。",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2025-06-25 腾讯网最新报道",
            "quality": 40,
            "quality_reason": "7 大类 33 岗全列 + 福利",
            "authenticity": 24,
            "authenticity_reason": "腾讯网新闻报道",
            "total": 94,
            "grade": "A",
        },
    },
    # ========== 字节跳动（实习岗 8 条新增）==========
    {
        "id": "JD-B010",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "字节跳动 ByteIntern 2027 届转正实习生（7000+ 名）",
        "salary_range": "未披露",
        "location": "北京 / 上海 / 深圳 / 杭州 / 成都",
        "source_url": "https://jobs.bytedance.com/campus",
        "source_quality": "trusted",
        "full_text": "ByteIntern：面向 2027 届毕业生（2026 年 9 月 - 2027 年 8 月期间毕业），为符合岗位要求的同学提供转正机会。\n\n2026 年招聘规模：\n- 字节跳动启动史上规模最大 ByteIntern 计划\n- 面向全球高校拟招聘超 7000 名 2027 届毕业生\n- 研发类岗位 Offer 数量超 4800 个，创历史新高\n- 所有岗位均提供转正机会，整体转正率预计超 50%\n\nAI 类在招岗位：\n- AIGC 算法实习生（智能创作团队）\n- 大模型算法实习生（开发者服务 / Data AML）\n- 豆包大模型算法研究实习生（机器学习中台）\n- 算法实习生（AI 数据与安全）\n- 算法实习生（AI 应用与创新）\n- ByteIntern 多业务方向\n\n工作地点：北京、上海、深圳、杭州、成都等\n\n投递通道：jobs.bytedance.com/campus",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2026-03-06 字节官方启动 2027 届实习",
            "quality": 42,
            "quality_reason": "招聘规模 + AI 类岗位 + 工作地点全列",
            "authenticity": 28,
            "authenticity_reason": "字节官方校招网站",
            "total": 100,
            "grade": "A",
        },
    },
    {
        "id": "JD-B011",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "字节跳动 Seed Top Seed 大模型顶尖人才计划（2026/27 届博士）",
        "salary_range": "未披露",
        "location": "北京 / 上海 / 深圳 / 杭州 / 成都 / 新加坡 / 悉尼 / 西雅图 / 圣何塞 / 圣地亚哥",
        "source_url": "https://www.bytedance.com/en/position",
        "source_quality": "trusted",
        "full_text": "团队：字节跳动 Seed（基础研究团队）\n\n招聘对象：\n- 全职岗位：博士同学（2026 年 9 月 - 2027 年 8 月期间毕业）\n- 实习岗位：在校博士同学（2026 年 9 月及以后毕业）\n\n研究方向与课题：\n1. 大模型应用\n2. 搜索 / 推荐 / 广告\n3. 计算机体系结构与系统优化\n4. 安全 / AI Safety\n5. 硬件\n6. AI Coding\n7. AIGC\n8. 视频架构\n9. AI for Science\n\n计划优势：\n- 字节唯一为强化大模型人才长期吸引与激励而设立专门的\"虚拟股\"\n- 顶级研究团队（谷歌 DeepMind 副总裁吴永辉等带队）\n- 不限专业背景，更关注研究潜力\n- 招聘标准极高：寻找大模型领域前 5% 的人\n- 2027 届校招计划招募约 100 位大模型方向优秀人才\n- 2026 届 Top Seed 计划招募约 30 位顶尖应届博士",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2025-04-01 字节 Seed 官方启动",
            "quality": 45,
            "quality_reason": "招聘对象 + 9 大研究方向 + 福利全列",
            "authenticity": 28,
            "authenticity_reason": "字节官方 + 多家媒体（环球网/腾讯/网易）",
            "total": 100,
            "grade": "A",
        },
    },
    {
        "id": "JD-B012",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "字节跳动 Seed-大模型应用算法实习生/校招",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://bbs.pku.edu.cn/v2/mobile/post-read.php?bid=896&threadid=18969570",
        "source_quality": "trusted",
        "full_text": "团队：字节跳动 Seed 团队\n\n实习、校招、社招都有\n\n岗位职责：\n1. 利用大模型优化搜索相关性、权威性、时效性等模型，解决各种复杂长尾查询的 Ranking 问题\n2. 利用大模型做 DOC 理解，筛选优质 DOC 以及更好支持在线检索\n3. 大模型在搜索召回和粗排等阶段的应用\n\n任职要求：\n1. 优秀的代码能力、数据结构和基础算法功底，熟练掌握 C/C++ 或 Python\n2. 熟悉深度学习和 LLM 相关的算法和技术，有一定的算法应用实习经验\n3. 良好的沟通协作能力，有出色的数据和问题分析能力\n4. 搜索算法经验以及 ACM/ICPC/NOI/IOI/Top Coder/Kaggle 等比赛获奖者优先\n\n投递邮箱：357152862@qq.com",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "北大 BBS 实习帖",
            "quality": 36,
            "quality_reason": "职责 3 项 + 任职要求 4 项",
            "authenticity": 22,
            "authenticity_reason": "北大 BBS（团队直推）",
            "total": 80,
            "grade": "A",
        },
    },
    {
        "id": "JD-B013",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "字节跳动 Data 电商团队 大模型算法实习生",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://www.sohu.com/a/841375193_121119001",
        "source_quality": "trusted",
        "full_text": "团队：字节跳动 Data-电商团队\n\n岗位职责：\n1. 电商场景下多模态大模型的技术探索，包括多模态大模型的 CPT、SFT、RLHF，并实现业务落地\n2. 电商场景下的机器审核场景 Benchmark 构建、大模型预训练与微调、Agent 搭建\n\n岗位要求：\n1. 代码能力、深度模型工程能力优秀，有相关论文、比赛、项目经历者优先\n2. 能实习 6 个月以上，2026 届应届生优先\n3. 有大模型/多模态大模型（包括不限于 llama/llava/Qwen 等）学习基础、模型训练基础（SFT 等）、相关项目比赛经历优先\n4. 有基础模型（包括不限于 CLIP/Beit 等）大规模预训练经验（预训练/下游微调等）、项目比赛经历优先\n\n福利待遇：\n1. 实习工资待遇好、福利待遇完善\n2. 业务场景核心，项目完成度好的同学未来有机会转正留用\n\n投递方式：chenhaobo.1013@bytedance.com",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "搜狐 2024 内推帖（持续）",
            "quality": 36,
            "quality_reason": "职责 2 项 + 任职要求 4 项 + 福利 2 项",
            "authenticity": 22,
            "authenticity_reason": "搜狐转载内推（带 HR 邮箱）",
            "total": 80,
            "grade": "A",
        },
    },
    {
        "id": "JD-B014",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "字节跳动 大模型算法实习生 - 开发者 AI 团队",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://jobs.bytedance.com/campus/position/7451809372411300103",
        "source_quality": "trusted",
        "full_text": "日常实习：面向全体在校生，为符合岗位要求的同学提供为期 3 个月及以上的项目实践机会。\n\n团队介绍：字节跳动开发者 AI 团队致力于探索 AI 技术在研发体系上应用和落地，覆盖场景包括 AI for Code、AI 在 DevOps 全流程中的落地。\n\n岗位职责：\n1. 负责代码场景的效果优化，深入研究 LLM 后训练等相关技术，提高算法准确率和效率\n2. 分析业务需求，设计并实现适用于不同场景的算法解决方案\n3. 持续跟进 LLM 前沿技术，基于 LLM 完成在代码领域中的复杂任务\n\n职位要求：\n1. 硕士及以上学位在读，计算机、软件工程、人工智能等专业优先\n2. 具有数据建设、指令微调和模型建设经验，具备优秀的代码能力\n3. 熟悉大模型训练、RL 算法者优先；在大模型领域发表过论文者优先\n4. 能连续实习 6 个月及以上，每周出勤 4 天及以上",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "字节官方招聘网站 2026 当季",
            "quality": 38,
            "quality_reason": "团队介绍 + 职责 3 项 + 任职要求 4 项",
            "authenticity": 28,
            "authenticity_reason": "字节官方招聘网站（recomId 来源）",
            "total": 96,
            "grade": "A",
        },
    },
    {
        "id": "JD-B015",
        "company": "字节跳动",
        "role_category": "test_qa",
        "job_type": "ai_test",
        "title": "字节跳动 质量技术团队 大模型算法实习生 - 智能交付",
        "salary_range": "未披露",
        "location": "北京 / 上海 / 深圳 / 杭州 / 成都",
        "source_url": "https://jobs.bytedance.com/campus",
        "source_quality": "trusted",
        "full_text": "ByteIntern：面向 2027 届毕业生（2026 年 9 月 - 2027 年 8 月期间毕业）\n\n团队：字节跳动质量技术团队，聚焦质量领域前沿创新，打造稳定、高效、领先的质量技术，深度赋能抖音、今日头条、豆包、电商等亿级用户产品。我们通过 AI 来检测代码、架构、产品的缺陷、风险和效果。聚焦智能缺陷检测、GUI agent、AI 评测等前沿方向。\n\n岗位职责：\n1. 负责大模型技术在软件智能交付领域的相关应用技术研发，业务场景包括但不限于知识图谱、代码生成、智能交互、风险预测挖掘、智能归因、缺陷修复、故障自愈\n2. 洞察 AIGC 等前沿技术领域的最新研究成果，探索工业领域落地可行性\n3. 探索大模型技术在研发效能领域中的落地应用\n4. 深度参与项目研发，与产品和业务团队同学保持密切配合\n\n亮点：聚焦 AI 重构测试流程，提升研发效能，从\"自动化\"到\"智能化\"的质量保障新路径。",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2026 当季 ByteIntern",
            "quality": 38,
            "quality_reason": "团队介绍 + 职责 4 项",
            "authenticity": 28,
            "authenticity_reason": "字节官方招聘网站",
            "total": 96,
            "grade": "A",
        },
    },
    {
        "id": "JD-B016",
        "company": "字节跳动",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "字节跳动 豆包大模型 机器学习方向算法实习生",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://www.sohu.com/a/878735180_121956424",
        "source_quality": "trusted",
        "full_text": "团队：字节跳动豆包大模型团队（2023 年成立）\n\n研究方向：自然语言处理（NLP）、计算机视觉（CV）、语音识别等多个领域，分布于中国、新加坡和美国等地\n\n具体的岗位职责：\n1. 参与字节跳动机器学习平台的开发与维护\n2. 参与设计和实现机器学习基础设施、框架及工具链\n3. 共同开发和优化自动评估大模型的技术\n4. 探索最新的机器学习技术\n\n岗位要求：\n1. 能够保证至少 3 个月的实习时间\n2. 扎实掌握计算机数据结构、操作系统和网络等基础知识\n3. 熟练使用 Python 或 Golang 编程语言\n4. 加分项：了解大模型、多模态大模型、智能代理；MySQL、Redis、Kafka、Ray、HDFS、Spark、Flink 等服务端和大数据开发经验",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "搜狐 2025 内推帖",
            "quality": 36,
            "quality_reason": "职责 4 项 + 任职要求 4 项",
            "authenticity": 22,
            "authenticity_reason": "搜狐转载内推",
            "total": 80,
            "grade": "A",
        },
    },
    # ========== 腾讯（实习岗 3 条新增）==========
    {
        "id": "JD-T008",
        "company": "腾讯",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "腾讯 多模态大模型日常算法实习生-2026 届",
        "salary_range": "未披露",
        "location": "上海",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "团队：腾讯游戏场景下的多模态大模型算法团队\n\n岗位职责：\n游戏场景下的多模态大模型算法模型构建，任务包括但不限于：游戏场景下的图像理解、多模态等领域的多模态大模型能力建设和工程落地\n\n岗位要求：\n1. 计算机、数学、统计等相关专业研究生及以上学历，或取得读研的本科生\n2. 在多模态大模型方面有一定研究基础，熟悉主流多模态大模型和算法\n3. 较强的工程实现能力，熟练掌握 Python、PyTorch\n4. 有相关项目、竞赛获奖、论文发表者优先\n5. 优秀者沟通表达能力、自驱学习能力\n6. 工作地为上海，实习时间 6 个月以上，长期实习者优先，优秀者可留用\n7. 面向 2026 年及以后毕业的同学",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 38,
            "quality_reason": "职责 + 任职要求 7 项",
            "authenticity": 28,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 94,
            "grade": "A",
        },
    },
    {
        "id": "JD-T009",
        "company": "腾讯",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "腾讯 2026 实习生招聘（10000+ 实习岗，AI 大幅扩招）",
        "salary_range": "未披露",
        "location": "深圳 / 北京 / 广州 / 上海 / 杭州 / 成都 + 全球",
        "source_url": "https://careers.tencent.com",
        "source_quality": "trusted",
        "full_text": "腾讯宣布正式启动 2026 实习生招聘，全球招 10000+ 位实习生。岗位涉及技术研究、软件开发、产品等。\n\n面向对象：在 2026 年 9 月 - 2027 年 12 月期间的在校大学生\n\n2026 实习生招聘规模：\n- 三年内新增 28000 个校招实习岗位，并加大转化录用\n- 仅 2025 年就会迎来 10000 名校招实习生岗位\n- 六成面向技术人才开放\n- 2026 实习生招聘技术类扩招 36%，产品类扩招 39%\n- AI 相关岗位大幅扩招\n\n招聘岗位涵盖技术、产品、设计、市场、职能等五大类 70 余种岗位，包括大模型、研发、算法、市场、策划、运营、销售、美术等多个岗位职能。\n\n工作地点：深圳、北京、广州、上海、杭州、成都六个城市（深圳岗位占比最高），海外覆盖 20 多个国家和地区（新加坡、美国、英国、日本、荷兰等）",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2025-03-06 腾讯官方启动 2026 实习",
            "quality": 40,
            "quality_reason": "招聘规模 + 岗位类型 + 工作地点全列",
            "authenticity": 28,
            "authenticity_reason": "腾讯官方招聘 + 多家媒体",
            "total": 98,
            "grade": "A",
        },
    },
    {
        "id": "JD-T010",
        "company": "腾讯",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "腾讯 2026 校招 + AI 产品经理培训生项目",
        "salary_range": "未披露",
        "location": "深圳 / 北京 / 上海 / 广州 / 杭州 / 成都",
        "source_url": "https://careers.tencent.com",
        "source_quality": "trusted",
        "full_text": "腾讯 2026 校园招聘正式启动。本次招聘面向 2025 年 1 月至 2026 年 12 月期间毕业的大学生，开放技术类、产品类、设计类、市场类、职能类等五大类 70 余种岗位。\n\nAI 人才布局：\n1. 2026 青云计划（已 6 月初启动）\n2. AI 产品经理培训生项目（8 月上旬启动）\n\n岗位亮点：\n- 重点放在 AI 领域\n- 后台开发、PC 客户端开发、移动客户端开发、游戏客户端开发等软件开发类岗位\n- 自然语言处理方向、计算机视觉方向、高性能计算方向、基础架构方向等技术研究岗位\n\nAI 产培生项目：是腾讯产品经理培训生项目的\"升级版\"，面向全球招聘顶尖 AI 产品人才，通过系统培养、专项训练、跨界学习等方式，助力优秀 AI 产品经理快速成长。\n\n海外校招遍布全球，覆盖 20 多个国家和地区，包括新加坡、美国、英国、日本、荷兰等。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2025-08-06 腾讯官方启动",
            "quality": 36,
            "quality_reason": "AI 人才布局 + 岗位亮点",
            "authenticity": 26,
            "authenticity_reason": "腾讯官方招聘 + 潮新闻报道",
            "total": 90,
            "grade": "A",
        },
    },
    # ========== 美团 / 京东 / 蚂蚁 / 华为 / 小米 ==========
    {
        "id": "JD-M009",
        "company": "美团",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "美团基础研发平台 大模型算法实习生（评测）",
        "salary_range": "未披露",
        "location": "北京 / 上海",
        "source_url": "https://www.liepin.com",
        "source_quality": "trusted",
        "full_text": "团队：美团基础研发平台，核心是\"零售+科技\"的战略定位\n\n岗位职责：\n负责 LLM 大模型评测算法的研究以及评测模型的训练、优化：\n1. 深入理解大规模语言模型的模型结构、训练过程以及评测方案\n2. 构建 Data-Centric 的数据-训练-评测闭环\n3. 追踪大模型方向的前沿进展\n\n岗位基本需求：\n1. 硕士及以上学历，计算机、数学、统计学或相关专业\n2. 熟悉 Java/Python/C++ 等编程语言\n3. 具有机器学习或深度学习算法的基础知识\n4. 具备 Kaggle 等机器学习比赛获奖、NeurIPS/ACL/EMNLP 顶会论文者优先",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "猎聘 2026 当季",
            "quality": 38,
            "quality_reason": "职责 3 项 + 任职要求 4 项",
            "authenticity": 24,
            "authenticity_reason": "猎聘一手实习帖",
            "total": 86,
            "grade": "A",
        },
    },
    {
        "id": "JD-M010",
        "company": "美团",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "美团到店广告 大模型算法实习生（大模型/因果推断方向）",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://www.zhipin.com/job_pk/016e2c9f9c5d02e51Hd539m9EltV.html",
        "source_quality": "trusted",
        "full_text": "团队：美团到店广告平台\n\n岗位职责（以下任一）：\n1. 参与到店广告业务智能问答机器人的研发与业务落地，优化主动拉新与维护场景的任务型对话能力\n2. 参与到店广告业务智能选商策略的迭代，基于因果推断、元学习、运筹优化等技术\n\n岗位要求：\n1. 硕士及以上学历，计算机、人工智能等相关专业背景\n2. 具备良好的编程能力，熟悉 tensorflow/pytorch/spark 至少一种计算框架\n3. 具备强烈的进取心、求知欲及团队合作精神\n4. 加分项：对大语言模型 prompt 工程与微调、因果推断、深度学习与运筹优化等其中一项技术有实践经验；国际顶级会议论文发表",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "BOSS 直聘 2026 当季",
            "quality": 34,
            "quality_reason": "职责 2 项 + 任职要求 4 项",
            "authenticity": 26,
            "authenticity_reason": "BOSS 直聘一手",
            "total": 86,
            "grade": "A",
        },
    },
    {
        "id": "JD-M011",
        "company": "美团",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "美团 语音大模型算法实习生",
        "salary_range": "3000-4000 元/月",
        "location": "北京 / 上海",
        "source_url": "https://www.liepin.com",
        "source_quality": "trusted",
        "full_text": "团队：美团语音相关业务\n\n岗位职责：\n1. 参与美团语音相关产品的 TTS、ASR、多模态交互模型等场景的效果评估\n2. 深入业务结合业务需求痛点，设计完备的算法效果质量保障、评测方案\n3. 推动通用人工智能评测方案的升级迭代\n\n任职要求：\n- 硕士及以上学历\n- 熟悉深度学习、语音算法相关知识",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "猎聘 2026 当季",
            "quality": 28,
            "quality_reason": "职责 3 项 + 任职要求 2 项",
            "authenticity": 24,
            "authenticity_reason": "猎聘一手实习帖",
            "total": 76,
            "grade": "A",
        },
    },
    {
        "id": "JD-M012",
        "company": "美团",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "美团大模型基座团队 日常实习生",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://www.zhipin.com/gongsir/c3c269e42b4ec7e00HB40969FQ.html",
        "source_quality": "trusted",
        "full_text": "团队：美团大模型基座团队\n\n岗位职责：\n1. 探索 LLM 前沿领域研究，包括但不限于数据建设、模型预训练、模型压缩、推理优化、逻辑推理、智能体、MoE、Scaling law 和模型评估\n2. 负责优化和提升 LLM 对齐效果，包括数据质量优化、指令微调、奖励模型优化、强化学习（RL）策略迭代\n\n岗位基本要求：\n1. 计算机科学、数学、统计学或相关领域的硕士或博士学位\n2. 熟悉 Python、Java 等至少一种编程语言与深度学习框架\n3. 具备 1 年以上 NLP 经验，熟悉 BERT、GPT 等模型\n4. 4 个月以上，每周到岗 4 天以上\n\n岗位亮点：\n1. 能够接触到丰富 GPU 算力和海量数据\n2. 能够触达丰富的业务",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "BOSS 直聘 2026 当季",
            "quality": 38,
            "quality_reason": "职责 2 项 + 任职要求 4 项 + 福利 2 项",
            "authenticity": 26,
            "authenticity_reason": "BOSS 直聘一手",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-M013",
        "company": "美团",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "美团 2027 届转正实习（3000+ 岗，北斗计划）",
        "salary_range": "未披露",
        "location": "北京 / 上海 / 深圳 / 成都 / 广州 / 香港 / 迪拜",
        "source_url": "https://campus.meituan.com",
        "source_quality": "trusted",
        "full_text": "美团 2026 年春季校园招聘：\n- 面向 2026 届毕业生补招至 6000 人\n- 面向 2027 届毕业生开放超过 3000 个转正实习岗位\n- 覆盖技术、产品、商业分析、运营等方向\n\n北斗计划（全年开放）：\n- 面向全球招募尖端校园科技人才\n- 重点聚焦于大模型基座、大模型应用、自动驾驶、无人机、智能决策等前沿技术方向\n\n食杂零售管培生计划：\n- 旨在培养高潜力零售管理人才",
        "scores": {
            "timeliness": 30,
            "timeliness_reason": "2025-03-04 美团官方启动 2026 春招",
            "quality": 36,
            "quality_reason": "招聘规模 + 北斗计划 + 食杂零售管培生",
            "authenticity": 26,
            "authenticity_reason": "美团官方招聘 + 每日经济新闻",
            "total": 92,
            "grade": "A",
        },
    },
    {
        "id": "JD-J007",
        "company": "京东",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "京东 大模型算法工程师实习（RAG/Agent/Knowledge Graph）",
        "salary_range": "未披露",
        "location": "北京",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "团队：京东 AI 平台\n\n岗位职责：\n1. 负责基于大模型的算法应用，持续优化 Agent 算法效率和准确性\n2. 研究并实现基于 RAG 的知识增强技术，以提高模型在特定领域的知识理解和生成能力\n3. 负责知识库的构建、维护和优化，包括知识抽取、知识融合、知识表示和知识检索\n4. 与产品团队紧密合作，将研发的技术成果应用于产品\n5. 跟踪最新的人工智能技术发展\n\n岗位要求：\n1. 26 届优先，计算机科学、人工智能或相关领域硕士及以上学历\n2. 熟练掌握 Python 编程语言，有良好的算法和数据结构基础\n3. 有 LangChain 框架经验、有大模型训练和调优经验者优先\n4. 对 Agent、RAG、知识图谱、自然语言处理等技术有深入理解和实践经验",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 38,
            "quality_reason": "职责 5 项 + 任职要求 4 项",
            "authenticity": 26,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-AT001",
        "company": "蚂蚁集团",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "蚂蚁集团 2026 春招（70%+ AI 岗，大模型/多模态/数据智能）",
        "salary_range": "未披露",
        "location": "杭州 / 上海 / 北京 / 香港 / 旧金山 / 伦敦",
        "source_url": "https://talent.antgroup.com",
        "source_quality": "trusted",
        "full_text": "蚂蚁集团 2026 年度春季校园招聘\n\n招聘规模：\n- 技术类岗位占比 85%\n- 超过 70% 岗位与人工智能直接相关\n- 重点布局大模型算法、多模态生成、数据智能、基础平台研发及 AI 安全\n\n招聘对象：面向全球高校，工作地点覆盖 6 城\n\n多模态算法实习岗（智能引擎事业群）：\n- 250-300 元/天，5 天/周，3 个月以上\n- 解决蚂蚁集团中搜索、推荐、广告、安全等多模态场景下的技术难题\n- 硕士及以上学位，图像/NLP/语音识别/视频/CS 等相关领域",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2026-03-10 蚂蚁官方启动春招",
            "quality": 36,
            "quality_reason": "招聘规模 + 重点领域 + 实习岗薪资",
            "authenticity": 24,
            "authenticity_reason": "蚂蚁官方招聘 + 牛客 + 观点网",
            "total": 88,
            "grade": "A",
        },
    },
    {
        "id": "JD-H001",
        "company": "华为云",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "华为云 大模型算法实习（AI 云服务方向）",
        "salary_range": "300-500 元/天",
        "location": "杭州",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "团队：华为云 AI 云服务团队\n\n岗位职责：\n1. 负责 AI 云服务上的核心 AI 算法设计和开发\n2. 负责 ML/LLM/AIGC 等某一个或多个方向上的算法优化\n3. 负责 AI 算法的前沿技术跟踪和创新方案设计、实现\n\n岗位要求：\n1. 熟悉 ML/LLM/AIGC 等某一个或多个方向的计算引擎/框架/平台/算法\n2. 掌握 Python/Go/C++ 中至少一种编程语言\n3. 掌握 AI 平台工程优化经历\n4. 模型加速、量化、分布式训练经验优先\n5. AutoML 经验优先\n6. 熟悉 AI 硬件（GPU，Davinci 芯片等）架构、AI 算子加速库、分布式 AI 系统优先\n\n时间要求：5 天/周，最少 2 个月",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 38,
            "quality_reason": "职责 3 项 + 任职要求 6 项",
            "authenticity": 28,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 94,
            "grade": "A",
        },
    },
    {
        "id": "JD-X001",
        "company": "小米",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "小米 AI 人才专项（语音/Agent/VLA/端到端算法实习）",
        "salary_range": "未披露",
        "location": "北京 / 上海 / 深圳 / 武汉 / 西安 / 南京",
        "source_url": "https://campus.hr.xiaomi.com/",
        "source_quality": "trusted",
        "full_text": "小米集团 2027 届暑期实习招聘：\n- 面向 2027 届毕业生\n- 20 大职类——软件研发、算法、测试、运维、硬件研发、芯片、产品、运营、设计、市场、销售、职能、供应链、服务等\n\nAI 人才专项：\n- 大模型语音方向\n- AI Agent 开发\n- 具身基座 VLA 大模型研究员\n- 端到端算法研究员\n\n小米汽车专项：小米汽车 2027 届转正实习生火热招募\n\n网申截止：即日起至 2026 年 5 月 31 日（招满即止）\n\n投递通道：https://campus.hr.xiaomi.com/",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2026 当季小米暑期实习",
            "quality": 36,
            "quality_reason": "20 大职类 + AI 人才专项 + 汽车专项",
            "authenticity": 24,
            "authenticity_reason": "小米官方招聘 + 搜狐报道",
            "total": 88,
            "grade": "A",
        },
    },
    # ========== 创业公司 / 独角兽 / 上市公司 ==========
    {
        "id": "JD-F001",
        "company": "第四范式",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "第四范式 大模型算法实习（北京）",
        "salary_range": "200-400 元/天",
        "location": "北京",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "公司：第四范式（中国智能决策市场的最大参与者，2023 年发布自研多模态大模型产品\"式说\"）\n\n部门：科技部专注于 AI 大模型、计算机视觉、自然语言处理、机器学习、决策优化、语音等领域的前沿技术研究和应用落地\n\n岗位职责：\n1. 参与机器学习、强化学习等模型的研发、设计、训练调优和部署\n2. 将机器学习、强化学习领域的算法应用于实际场景\n3. 将实践中的创新点以 Github Repo/Paper/Tech Report 等形式开源\n\n岗位要求：\n1. 本科及以上学历，熟悉机器学习、深度学习、数据挖掘、强化学习等方向之一\n2. 熟练掌握 python/C++ 等编程语言\n3. 掌握 AutoML、强化学习、迁移学习、对抗学习、凸优化、搜索、推荐、图神经网络、知识图谱等\n4. 在 ICML/NeurIPS/ICLR/KDD/WebConf/AAAI/IJCAI 等国际顶级会议或期刊上发表过论文者优先\n5. 有大模型多模态领域相关技术经验或竞赛经验\n\n时间要求：本科，5 天/周，最少 3 个月",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 42,
            "quality_reason": "公司介绍 + 部门介绍 + 职责 3 项 + 任职要求 5 项",
            "authenticity": 28,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 98,
            "grade": "A",
        },
    },
    {
        "id": "JD-V001",
        "company": "vivo AI Lab",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "vivo AI Lab 多模态大模型算法实习生",
        "salary_range": "250-450 元/天",
        "location": "深圳",
        "source_url": "https://m.yupao.com/zhaogong/338947207.html",
        "source_quality": "trusted",
        "full_text": "团队：vivo AI Lab\n\n岗位职责：\n1. 掌握主流多模态大模型的架构与训练策略\n2. 探索前沿的端侧大模型方案，重点关注视觉模块的设计与优化\n3. 参与端侧多模态大模型的训练工作，评估新型结构的实际表现\n4. 整理研究成果，协助撰写并发表学术论文\n\n岗位要求：\n1. 可实习 6 个月及以上者优先考虑\n2. 本岗位拟招收 2 人，招满即止\n\n加分项：\n- 有顶会论文发表经历\n- 具备大型企业实习项目经验\n- 在机器学习相关竞赛中取得优异成绩\n- 拥有特殊的视觉语言模型（VLM）训练经验，例如 OCR 大模型训练背景",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "鱼泡直聘 2026 当季",
            "quality": 36,
            "quality_reason": "职责 4 项 + 加分项 4 项",
            "authenticity": 22,
            "authenticity_reason": "鱼泡直聘（可信，岗位描述详细）",
            "total": 82,
            "grade": "A",
        },
    },
    {
        "id": "JD-W001",
        "company": "金山办公",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "金山办公（WPS）大模型算法实习（武汉）",
        "salary_range": "未披露",
        "location": "武汉",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "公司：金山办公（WPS）\n地址：武汉洪山区关山大道新发展中心 A 座\n\n实习内容：\n1. 负责文本数据清洗、数据分析等相关工作\n2. 负责模型微调相关任务设计与调优\n3. 负责 AIGC 在办公场景领域的应用的研究及研发，主要场景为 Agent 搭建、代码生成、意图和多轮 function-calling 等\n\n岗位要求：\n1. 硕士及以上学历，人工智能、计算机科学、数学、统计、自动化等相关专业优先\n2. 扎实的算法基础，熟悉 LLM、NLP 相关算法和模型\n3. 动手能力强，有一定的编码与实战能力\n4. 责任心强，有较强的自驱力\n5. 每周至少保证 4 天的全职实习，能实习 3-6 个月\n\n投递邮箱：lijingyi@wps.cn",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 36,
            "quality_reason": "公司介绍 + 实习内容 3 项 + 任职要求 5 项",
            "authenticity": 26,
            "authenticity_reason": "牛客网一手实习帖（带 HR 邮箱）",
            "total": 88,
            "grade": "A",
        },
    },
    {
        "id": "JD-K001",
        "company": "Kimi 月之暗面",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "Kimi 月之暗面 穿越计划（顶尖人才校招实习）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "https://mp.weixin.qq.com/s/PZ9Tj5OL0df9r2qpUSuSrA",
        "source_quality": "trusted",
        "full_text": "团队：Kimi（月之暗面）\n\n计划名称：\"穿越计划\"顶尖人才校招项目\n\n面向人群：2027 届毕业生\n\n首批名额：仅 16 人\n\n硬性门槛：几乎没有硬性条件限制，不限岗位类型，不限专业、学历和经验，核心只看候选人的天赋与潜力\n\n核心福利：\n1. 入选者在通过 3-6 个月的实习考察后，即便尚未正式毕业，也将被直接授予公司期权\n2. 公司将按 2026 年实习开始时的当期期权单价授予期权，股数锁定，归属期随即开始计算\n\n公司风格：\n- 极度扁平化管理\n- 没有职级和强制 OKR\n- 创始人曾为招揽一名核心技术人才专程从北京飞赴深圳长谈十个小时\n\n投递方式：https://mp.weixin.qq.com/s/PZ9Tj5OL0df9r2qpUSuSrA（目前以邮件投递为主）",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "Kimi 公众号 / 微信官方",
            "quality": 36,
            "quality_reason": "项目名 + 福利 + 公司风格",
            "authenticity": 22,
            "authenticity_reason": "Kimi 官方公众号",
            "total": 82,
            "grade": "A",
        },
    },
    {
        "id": "JD-Q001",
        "company": "启元世界",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "启元世界 大模型算法实习生（杭州）",
        "salary_range": "未披露",
        "location": "杭州",
        "source_url": "https://www.nowcoder.com/jobs/detail/367875",
        "source_quality": "trusted",
        "full_text": "公司：启元世界\n\n职位描述：\n1. 积极跟进和探索大模型相关的前沿研究\n2. 参与大规模语言模型应用的算法研发与应用，针对多轮对话生成结果进行调优\n3. 模型预训练相关的数据处理\n\n职位要求：\n1. 机器学习、统计、数学、计算机科学相关专业硕士、博士，或优秀本科\n2. 深度学习方面具备扎实的理论基础和实践经验，熟练掌握 Python/C++/Java 中至少一门语言\n3. 熟悉深度学习框架的使用，包括 Pytorch、transformers 等；熟悉知识问答、搜索、知识图谱等\n4. 熟悉主流 LLM 模型，包括预训练、微调、RLHF 等阶段，发表过相关论文者优先\n5. 有线上对话系统，LLM 模型训练和部署经验者优先\n6. 有流畅的英文科学文献阅读能力",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "牛客网一手实习帖",
            "quality": 38,
            "quality_reason": "职责 3 项 + 任职要求 6 项",
            "authenticity": 26,
            "authenticity_reason": "牛客网一手实习帖",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-BD001",
        "company": "BOSS 直聘",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "BOSS 直聘南北阁 大模型研发团队 大模型算法实习生",
        "salary_range": "500 元/天起",
        "location": "北京太阳宫冠捷大厦",
        "source_url": "https://www.sohu.com/a/870948231_121119001",
        "source_quality": "trusted",
        "full_text": "公司：BOSS 直聘大模型研发团队\n团队核心成员均为北大毕业，从零自研南北阁系列模型在 Opencompass、FlagEval、AlpacaEval 等国内外知名 Leaderboard 中位于前列，相关成果发表于 NeurIPS/ICLR/NAACL 等顶会。\n\n岗位职责：\n1. 参与百 B 级参数大模型的架构设计与分布式训练优化\n2. 研发高效数据清洗 Pipeline，构建领域增强预训练语料库\n3. 创新模型结构及 KV 计算，优化 Prefill/Decode 两端\n4. 探索 SFT/RL 等对齐技术，提升模型指令遵循与专项能力\n\n岗位要求：\n1. 计算机/数学/EE 相关专业，熟练掌握 PyTorch/TensorFlow 框架\n2. 扎实的算法基础和编码能力\n3. 持续跟踪 LLM 领域进展，能复现最新论文算法\n4. 保证 3 天/周以上出勤，持续实习 6 个月+\n\n你将收获：\n1. 行业竞争力日薪：500 元/天起，优秀者可面议\n2. 深度参与 AGI 进程：从预训练到应用落地的全链路实战\n3. 顶会级资源支持：千卡算力集群 + 闭源数据 + 定期论文研讨会\n4. 高转正优先级：表现优异者直通 2025/2026 校招\n\n投递方式：nanbeige@kanzhun.com",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "搜狐 2025-03 内推帖",
            "quality": 42,
            "quality_reason": "团队介绍 + 职责 4 项 + 任职要求 4 项 + 福利 4 项",
            "authenticity": 24,
            "authenticity_reason": "搜狐转载内推（带 HR 邮箱）",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-S001",
        "company": "深言科技",
        "role_category": "data_annot",
        "job_type": "ai_pm",
        "title": "深言科技（清华 NLP 孵化） 大模型数据标注实习生",
        "salary_range": "350-400 元/天",
        "location": "北京海淀区东升大厦",
        "source_url": "https://www.zhipin.com/job_pk/0f9cdba024c3b6541HJy2Nq5FlBZ.html",
        "source_quality": "trusted",
        "full_text": "公司：深言科技（DeepLang AI）—— 孵化自清华大学计算机系自然语言处理实验室（THUNLP）和北京智源人工智能研究院（BAAI），由欧洲科学院院士领衔担任首席科学家。\n\n职位：大模型数据标注实习生\n\n工作亮点：\n1. 背靠清华大学自然语言处理实验室，有国内顶尖 NLP 技术支持\n2. 目标远大：做国内最好的大规模中文预训练语言模型\n3. 团队有自研大规模中文预训练模型经验，有深厚的 NLP 知识积累\n4. 能与学术牛人一起交流讨论，探索最前沿的技术\n\n其它福利：\n1. 薪资：350-400 元/天，餐补 30 元/天\n2. 地点：北京市海淀区东升大厦 A 座 501\n3. 福利：Mac 笔记本电脑、高清显示器、人体工学椅、免费无限量零食车、免费健身房、下午茶、团建等等",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "BOSS 直聘 2026 当季",
            "quality": 36,
            "quality_reason": "公司背景 + 工作亮点 4 项 + 福利 3 项",
            "authenticity": 26,
            "authenticity_reason": "BOSS 直聘一手实习帖",
            "total": 88,
            "grade": "A",
        },
    },
    {
        "id": "JD-SH001",
        "company": "MiniMax",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "MiniMax 大模型算法实习生（多模态/数据方向）",
        "salary_range": "未披露",
        "location": "上海",
        "source_url": "https://www.zhipin.com/job_detail/9a20df9bfc480f3d03R60tS0ElBQ.html",
        "source_quality": "trusted",
        "full_text": "团队：MiniMax 大模型团队（自研 MiniMax / MiniMax-01 系列）\n\n岗位职责：\n1. 研发超大规模多模态模型，进行极致的系统优化\n2. 将多模态大模型应用于图像理解、逻辑推理等领域\n3. 大模型训练数据构建\n\n职位要求：\n1. 技术热情：相信 AGI 技术的潜力，会主动了解行业进展，敢于挑战技术边界\n2. 对数据有理解，有大规模数据处理经验\n3. 优秀的代码能力和机器学习基础\n4. 熟练使用 AI 工具（ChatGPT 等）\n5. 理解多模态视觉理解的原理，有实际研发经验者优先\n6. 能够独立解决复杂的技术问题，主导或者参与过具有影响力的项目优先",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "BOSS 直聘 2026 当季",
            "quality": 34,
            "quality_reason": "职责 3 项 + 任职要求 6 项",
            "authenticity": 24,
            "authenticity_reason": "BOSS 直聘一手",
            "total": 82,
            "grade": "A",
        },
    },
    {
        "id": "JD-A014",
        "company": "AMD",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "AMD 大模型压缩算法实习生（量化/剪枝/蒸馏）",
        "salary_range": "未披露",
        "location": "北京朝阳安贞门",
        "source_url": "https://bbs.pku.edu.cn/v2/mobile/post-read.php?bid=896&threadid=18975065",
        "source_quality": "trusted",
        "full_text": "团队：AMD AI 研究团队\n\n实习时间：2026.01 - 2026.06\n\n职位描述：负责 LLM 量化（INT4/INT8/FP8）、剪枝、蒸馏等技术的算法研究或工程落地\n\n任职要求：\n1. 掌握 Python/C++ 编程，具备扎实的算法与数据结构基础\n2. 熟悉常见模型结构：如 Transformer、Resnet 等，了解大模型（如 LLaMA、QWEN、GPT 系列）的结构特点\n3. 掌握至少 1 种模型压缩技术（如量化、剪枝、蒸馏），有实际工程落地优先\n4. 发表过 ICML、NIPS、ACL、CVPR 等顶会优先\n\n其他：\n1. base 在北京市朝阳区安贞门地铁站附近，可远程\n2. 有转正名额给前 mentor 招人，组内氛围极其 nice\n3. mentor 人非常好，做的方向属于 LLM 落地很火的方向，能学到很多\n\n简历收件邮箱：larryli2@amd.com",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "北大 BBS 实习帖",
            "quality": 36,
            "quality_reason": "职位描述 + 任职要求 4 项 + 其他福利 3 项",
            "authenticity": 22,
            "authenticity_reason": "北大 BBS（团队直推）",
            "total": 80,
            "grade": "A",
        },
    },
    {
        "id": "JD-G001",
        "company": "广汽集团",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "广汽集团 多模态大模型算法研发实习生",
        "salary_range": "120 元/天",
        "location": "广州",
        "source_url": "https://m.yingjiesheng.com/jobdetail/171993852",
        "source_quality": "trusted",
        "full_text": "公司：广州汽车集团股份有限公司\n\n岗位职责：\n1. 多模态大模型技术调研、代码复现和微调\n2. 基于多模态大模型的应用开发，包括但不限于多模态内容生成、车内外多模态感知等\n3. 多模态大模型的小型化开发、车端/云端部署等\n4. 大模型相关工具化、数据处理需求\n\n岗位要求：\n1. 硕士在校学生，计算机、人工智能、数学等相关专业背景\n2. 熟练使用 Python、C/C++ 编程\n3. 有视觉、机器人、智能化平台开发经验者优先，如 Pytorch、DeepSpeed、OpenCV 等\n4. 执行力强，有良好的沟通和团队协作能力\n5. 表现优秀会酌情考虑获得转正机会",
        "scores": {
            "timeliness": 22,
            "timeliness_reason": "应届生求职网 2024 实习帖",
            "quality": 32,
            "quality_reason": "职责 4 项 + 任职要求 5 项",
            "authenticity": 22,
            "authenticity_reason": "应届生求职网转载",
            "total": 76,
            "grade": "A",
        },
    },
    {
        "id": "JD-BD002",
        "company": "百度",
        "role_category": "data_annot",
        "job_type": "ai_pm",
        "title": "百度 AI 大模型理工科数据分析师实习生",
        "salary_range": "300-360 元/天",
        "location": "北京",
        "source_url": "https://www.zhipin.com/job_pk/0f9cdba024c3b6541HJy2Nq5FlBZ.html",
        "source_quality": "trusted",
        "full_text": "公司：百度\n\n岗位职责：\n1. 负责大模型理工科相关的数据分析和规范制定\n2. 负责大模型理工科的数据标注管理和审核\n3. 负责统筹和协调项目进展等\n\n任职资格：\n1. 理工科如：物理、材料学、化学、生物等专业\n2. 计算能力强、会使用 LaTeX 语法者优先\n3. 在校专业成绩优秀者优先\n4. 对 AI 技术感兴趣，积极主动，善于沟通\n5. 知识面广，爱好广泛，有好奇心\n6. 学习能力和抗压能力强，认真细心、踏实负责者优先\n\n附加 AI 大模型数据标注实习：\n- 500-550 元/天\n- 主要负责根据客户/PM 提供的项目信息，通过试标数据完善内容标准\n- 研究生及以上（985、211），专业为汉语言文学、中国古典文献学、新媒体专业相关者优先",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "BOSS 直聘 2026 当季",
            "quality": 34,
            "quality_reason": "岗位职责 3 项 + 任职资格 6 项",
            "authenticity": 24,
            "authenticity_reason": "BOSS 直聘一手",
            "total": 82,
            "grade": "A",
        },
    },
    {
        "id": "JD-SQ001",
        "company": "商汤科技",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "商汤科技 AI 先锋顶尖实习生（生成式 AI / 智能汽车）",
        "salary_range": "未披露",
        "location": "上海 / 北京",
        "source_url": "https://hr.sensetime.com/SU60fa3bdabef57c1023fc1cbc/pb/interns.html",
        "source_quality": "trusted",
        "full_text": "公司：商汤科技\n\n招聘项目：商汤「AI 先锋」顶尖实习生全球招募，面向 2027 届毕业生\n\n业务方向：\n1. 生成式 AI\n2. 传统 AI\n3. 智能汽车\n\n工作地点：上海、北京\n\n投递方式：https://hr.sensetime.com/SU60fa3bdabef57c1023fc1cbc/pb/interns.html",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "商汤官方招聘 2026 当季",
            "quality": 24,
            "quality_reason": "招聘项目 + 业务方向 + 工作地点",
            "authenticity": 26,
            "authenticity_reason": "商汤官方招聘",
            "total": 76,
            "grade": "A",
        },
    },
    # ========== 百运网（实习岗 4 条新增 - 用户手抄自 2026 春招海报）==========
    # Round 3.5 阈值调优样本（label 字段保留在 简历帮知识库/jd_samples.json）
    {
        "id": "JD-BY001",
        "company": "百运网",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "百运网 算法开发实习生（物流大模型应用）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "user_provided:百运网2026春招海报",
        "source_quality": "unverified",
        "full_text": "公司：百运网\n\n岗位职责：\n1. 参与公司物流业务场景的大模型应用开发与优化；\n2. 负责 Prompt 设计、效果调优及评测；\n3. 参与基于知识的 RAG 系统构建与优化；\n4. 协助开发 AI Agent 或自动化流程，提升作业效率；\n5. 与产品和业务团队协作，推动 AI 功能在实际业务中的落地。\n\n招聘要求：\n1. 计算机、人工智能、软件工程等相关专业，本科大三及以上或研究生在读；\n2. 熟悉 Python 编程，具备良好的代码能力；\n3. 了解大模型（LLM）的基本原理及应用方式，如 Prompt Engineering、RAG、Agent 等；\n4. 对 AI 在业务场景中的落地（如物流、运营效率提升等）有兴趣；\n5. 具备较好的逻辑思维能力和问题分析能力。",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "百运网 2026 春招海报",
            "quality": 36,
            "quality_reason": "职责 5 项 + 任职要求 5 项",
            "authenticity": 18,
            "authenticity_reason": "用户手抄自海报（二手，未上网验证）",
            "total": 78,
            "grade": "A",
        },
    },
    {
        "id": "JD-BY002",
        "company": "百运网",
        "role_category": "general",
        "job_type": "ai_eng",
        "title": "百运网 后端/全栈开发实习生（AI 系统对接）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "user_provided:百运网2026春招海报",
        "source_quality": "unverified",
        "full_text": "公司：百运网\n\n岗位职责：\n1. 参与 AI 系统功能模块开发；\n2. 协助完成 AI 模型接口的对接与部署；\n3. 负责日常业务系统的维护与 Bug 修复，确保系统稳定性。\n\n招聘要求：\n1. 计算机相关专业本科大三及以上，基础扎实；\n2. 熟练掌握 Typescript 或 Python，熟悉 SQL 数据库操作；\n3. 具备较强的代码编写能力，有过项目开发经验。",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "百运网 2026 春招海报",
            "quality": 28,
            "quality_reason": "职责 3 项 + 任职要求 3 项",
            "authenticity": 18,
            "authenticity_reason": "用户手抄自海报（二手，未上网验证）",
            "total": 70,
            "grade": "A",
        },
    },
    {
        "id": "JD-BY003",
        "company": "百运网",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "百运网 AI 产品实习生（物流场景）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "user_provided:百运网2026春招海报",
        "source_quality": "unverified",
        "full_text": "公司：百运网\n\n岗位职责：\n1. 协助梳理逻辑物流业务流程，识别 AI 提效点；\n2. 负责 AI 模块（如智能客服、自动单据识别）的原型设计与文档编写；\n3. 协调开发与算法进行功能验证。\n\n招聘要求：\n1. 工业工程、物流管理或计算机相关专业优先，本科大三及以上；\n2. 逻辑严密，能画流程图或高质量原型；\n3. 对 AI 落地有热情，能熟练使用各种 AI 效率工具。",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "百运网 2026 春招海报",
            "quality": 28,
            "quality_reason": "职责 3 项 + 任职要求 3 项",
            "authenticity": 18,
            "authenticity_reason": "用户手抄自海报（二手，未上网验证）",
            "total": 70,
            "grade": "A",
        },
    },
    {
        "id": "JD-BY004",
        "company": "百运网",
        "role_category": "test_qa",
        "job_type": "ai_test",
        "title": "百运网 测试开发实习生（AI 系统测试）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "user_provided:百运网2026春招海报",
        "source_quality": "unverified",
        "full_text": "公司：百运网\n\n岗位职责：\n1. 参与 AI 系统的功能测试与回归测试；\n2. 编写测试用例，记录并跟踪 Bug 修复进度；\n3. 在导师指导下编写自动化测试脚本或使用 AI 工具生成测试数据。\n\n招聘要求：\n1. 计算机相关专业，熟悉软件测试理论与流程，本科大三及以上；\n2. 至少掌握一门脚本语言（如 Python 或 Typescript）；\n3. 细心、有责任感，具备较强的逻辑分析和文档编写能力。",
        "scores": {
            "timeliness": 24,
            "timeliness_reason": "百运网 2026 春招海报",
            "quality": 28,
            "quality_reason": "职责 3 项 + 任职要求 3 项",
            "authenticity": 18,
            "authenticity_reason": "用户手抄自海报（二手，未上网验证）",
            "total": 70,
            "grade": "A",
        },
    },
    # ========== 2026-06-27 补充 10 份大厂 JD（user 截图手抄）==========
    {
        "id": "JD-A015",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_research",
        "title": "阿里巴巴 日常实习生-用户互动-AI Agent 优化工程师（训练/数据/评测）",
        "salary_range": "未披露",
        "location": "杭州",
        "source_url": "user_provided:阿里校招官网2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：阿里巴巴淘天集团\n更新时间：2026-06-24\n毕业起止时间：2027-03-01 ~ 2029-07-01\n岗位类别：技术类\n招聘项目：阿里巴巴日常实习生\n\n这是一个综合的 AI 推理、优化的技术岗位，适合希望从事以下工作的候选人投递：\n- 希望从事 AI 应用构建与模型优化工作的候选人\n- 希望从事 AI 应用数据构建与自动化评测工作的候选人\n- 希望从事多模态 AI 应用构建与算法优化工作的候选人\n\n围绕真实业务核心场景，参与 AI 应用的系统化构建与优化，把 AI 变为业务增长引擎，具体职责包括：\n1. AI 应用全生命周期演进：深度参与业务问题建模、应用架构设计、上下文工程、训练数据构建、自动化评估体系、模型后训练优化等；\n2. 数据飞轮构建：打造高质量数据生产链路，探索合成数据（Synthetic Data）与高效蒸馏技术方案，跑通\"业务-模型-反馈\"迭代闭环；\n3. 评测体系构建：面向业务目标，设计完备的 AI 应用效果评估体系，构建自动化评估框架，建立离线评估与在线业务指标联动的量化评估能力；\n4. 强化学习与奖励机制设计：构建可工程化的 Reward 体系与 RL 训练环境，提升模型在垂直业务场景中的可控性与泛化能力；\n5. AI 外部能力体系搭建：实现 AI 应用所需的知识库（RAG）、长短期记忆系统（Memory）、工具调用、多 Agent 协作框架等；\n6. 多模态 AI 应用开发：构建 AI 应用的多模态感知与推理能力，解决在 UI 自动化、视觉理解与审核、多模态会话等场景的落地应用问题。\n\n基础要求：\n1. 专业要求：计算机、数学、统计学等相关专业硕士/博士优先，优秀本科生不受限制；\n2. 模型理解与优化：深入理解 Transformer 和主流 LLM 模型架构演进原理，对后训练算法有实操经验和深刻认知，拥有 Agentic RL 训练实操经验者优先；\n3. AI 应用构建能力：掌握主流 AI 协议（MCP、Skills 等）、记忆系统（Memory）、知识库（RAG），独立开发过具备一定影响力的 AI 应用者优先；\n4. 代码与工程能力：较强 Python 编程能力，熟练掌握 PyTorch，了解大模型训练与推理框架（Megatron-LM、vLLM、DeepSpeed 等），能高效处理分布式环境下的工程问题；\n5. 数据构建能力：有很强的 Data-centric AI 的意识，精通后训练所需高质量数据挖掘与构造，具备合成数据（Synthetic Data）与动作轨迹（Trajectory）构建实操经验者优先；\n6. 评测能力：拒绝盲目调参，能针对 Agent 任务设计科学的评测体系（LLM-as-a-Judge），能基于评测结果精准分析和定位问题，具备复杂多步任务的量化评估能力者优先；\n7. 对新技术有近乎本能的渴望，能够独立阅读论文/技术报告等并快速复现，快速主动尝试落地先进开源项目，对主流 AI 开源项目有贡献者优先。\n\n加分项：\n1. 在 AI 顶会（ACL/EMNLP/ICLR/NeurIPS/ICML 等）发表大模型评测、数据合成、Agent、RL 相关一作或共一论文；\n2. 知名大模型评测框架或高质量开源数据核心贡献者；\n3. 极强的数学功底和逻辑分析能力，对高质量数据和评测有端到端闭环经验。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2026-06-24 阿里校招官网截图，2026 当季校招",
            "quality": 42,
            "quality_reason": "岗位职责 6 大项 + 基础要求 7 大项 + 加分项 3 项，字段完整",
            "authenticity": 22,
            "authenticity_reason": "用户从阿里校招官网截图手抄，URL 未在脚本中保留",
            "total": 92,
            "grade": "A",
        },
    },
    {
        "id": "JD-A016",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_test",
        "title": "阿里巴巴 日常实习生-智能体评测",
        "salary_range": "未披露",
        "location": "杭州",
        "source_url": "user_provided:阿里校招官网2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：阿里巴巴控股集团\n更新时间：2026-06-25\n毕业起止时间：2027-07-01 ~ 2030-01-01\n岗位类别：运营类\n招聘项目：阿里巴巴日常实习生\n\n岗位职责：\n1. 参与智能体安全评测相关工作，调研和研究大语言模型智能体的安全评估方法，协助搭建智能体安全评测框架，制定智能体规约。\n2. 执行智能体在提示注入、越狱攻击、权限滥用、数据泄露、多智能体协作风险等安全维度的评测任务，协助整理和构建安全评测数据集（Benchmark），跟进评测方案的迭代优化。\n3. 开展智能体安全领域的产品调研与竞品分析，收集和整理国内外智能体安全评测相关技术方案与行业动态，撰写调研报告。\n4. 配合团队完成安全评测相关的日常研究与技术支持工作。\n\n岗位要求：\n1. 硕士及以上学历，人工智能、计算机科学、网络安全等相关专业，能保证一定的实习时长（每周不少于 3 天，持续 3 个月以上）。\n2. 对大语言模型和智能体技术有一定了解，熟悉 ReAct、Tool Use 等常见智能体架构，了解过 AgentBench、GAIA、HarmBench 等评测基准者更佳。\n3. 具备较好的编程基础，熟悉 Python 开发，有 PyTorch、LangChain 等相关框架使用经验者优先。\n4. 具备良好的逻辑思维和信息检索能力，能够独立完成资料调研、数据整理和报告撰写工作。\n5. 具备扎实的数据分析能力，能独立设计实验、构建评测集，并擅长从数据中提炼洞察。\n6. 学习能力强，对智能体安全方向有浓厚兴趣，具备良好的沟通表达和团队协作意识。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2026-06-25 阿里校招官网截图，2026 当季校招",
            "quality": 40,
            "quality_reason": "岗位职责 4 项 + 岗位要求 6 项，字段完整",
            "authenticity": 22,
            "authenticity_reason": "用户从阿里校招官网截图手抄",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-A017",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "阿里巴巴 日常实习生-用户互动-AI 应用开发工程师",
        "salary_range": "未披露",
        "location": "杭州",
        "source_url": "user_provided:阿里校招官网2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：阿里巴巴淘天集团\n更新时间：2026-06-24\n毕业起止时间：2027-11-01 ~ 2029-09-30\n岗位类别：技术类\n招聘项目：阿里巴巴日常实习生\n\n聚焦核心业务场景，利用 Agent 等前沿技术推动 AI 落地。你将参与从需求洞察到系统构建的全流程，通过研发智能应用与工具，提升业务效率与效果，实现技术驱动业务增长的完整闭环，推动智能规模化演进，实现技术价值转化。\n\n具体职责包括以下相关方向的一项或多项：\n1. 需求理解与归因：\n- 深入业务场景，利用数据挖掘与特征分析完成现象归因；精准识别高价值问题，将模糊的业务痛点转化为明确的 AI 解决策目标。\n2. 架构设计：\n- 面向具体业务需求，设计 AI 原生系统架构；参与 Agent 系统核心模块的规划，包括记忆管理、推理策略与工具编排，兼顾架构的灵活性、可扩展性与工程可落地性。\n3. 知识与环境构建：\n- 搭建 AI 与现有业务系统的交互环境，涵盖 API 接入、RAG 知识库构建、记忆方案设计；持续优化召回质量与上下文注入策略，为模型提供准确、及时的执行环境与知识支撑。\n4. 核心能力实现：\n- 负责 Agent 关键模块的工程落地，实现意图识别、任务拆解与反思纠错闭环；封装标准化 SDK/API 服务，构建 Agent 观测体系，实现全链路追踪与多维归因分析。\n5. 系统迭代与演进：\n- 建立搭建自动化评测与回测机制，通过调优与 Case 分析不断收敛效果与性能提升的最优路径；沉淀方法论与可复用组件，推动 AI 能力从单点验证走向规模化落地。\n6. 性能优化：\n- 优化高并发场景下的系统性能，通过异步处理与降级策略保障稳定性，通过低侵入性观测手段保障系统的长期稳定运行。\n\n岗位要求：\n1. 基础条件\n- 计算机、软件工程、人工智能等相关专业优先。\n2. 专业能力\n- AI 编程工具重度玩家：Cursor、Claude code 等 AI 编程工具重度或顶级玩家，具备极强的 Prompt 编写与调优能力，有过完整的项目开发经验，理解如何让 AI 写出生产级代码。\n- 大模型能力理解与掌握：理解主流 LLM 的能力与局限，能够清晰拆解任务并通过 LLM 或确定性逻辑彻底实现，熟悉主流大模型的应用范式（Context Engineering、Prompt Engineering、Agent、工具/函数调用等等）及主流 Agent 框架（如 LangChain 等），具备大模型幻觉、Prompt 注入等风险的工程化应对思路。\n- 扎实的代码和工程能力：具备扎实的计算机基础知识，深入理解数据结构、算法、网络和操作系统等相关知识，能至少在一种主流编程语言（如 Java / Python / JS 等）上有深度的实践经验，掌握常见工程实践并具备优秀的 Coding 能力，能够根据场景灵活选型并快速上手。\n3. 能力特质\n- 学习能力：具备快速啃透前沿论文（Paper）的能力，并能将理论知识转化为工程代码。\n- 开放性与动手能力：拒绝纸上谈兵，有自己独立完成的小项目（开源项目或个人 Demo），展现极客精神。\n- 好奇心与想象力：面对未知事物有独特的想法，具备敏锐的问题定义能力和坚韧的解决问题能力。\n- 审美追求：技术亦有审美，鼓励你提出能打动人心、简洁优雅的好想法。\n- 高能动性：具备强烈的自驱力，能够主动探索边界，而不是等待被分配任务。\n\n加分项：\n- 有 AI 应用或 Agent 实际落地经验：包括不限于 RAG 系统、多智能体编排、结合 MCP、Skill 等的 Agent 项目，有可展示的项目/实习成果者优先。\n- 开源贡献或技术影响力：在 Github 上有高质量 AI 项目、技术博客或社区影响力。\n- 对 AI Infra 有基本理解：了解 vLLM、Ollama 等推理框架原理，理解延迟优化、KV cache 优化、流式输出等工程全局视角。\n- 在 CV（计算机视觉）或 NLP（自然语言处理）方向有扎实的理论基础，有实际业务场景模型训练（SFT、RL）经验的优先。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "2026-06-24 阿里校招官网截图，2026 当季校招",
            "quality": 44,
            "quality_reason": "6 大职责模块 + 3 大能力特质 + 4 项加分项，字段极完整",
            "authenticity": 22,
            "authenticity_reason": "用户从阿里校招官网截图手抄",
            "total": 94,
            "grade": "A",
        },
    },
    {
        "id": "JD-A018",
        "company": "阿里巴巴",
        "role_category": "algorithm",
        "job_type": "ai_eng",
        "title": "阿里巴巴 日常实习生-业务技术-AI Agent 优化工程师",
        "salary_range": "未披露",
        "location": "杭州",
        "source_url": "user_provided:阿里校招官网2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：阿里巴巴淘天集团\n更新时间：2026-06-24\n毕业起止时间：2025-06-30 ~ 2028-12-31\n岗位类别：技术类\n招聘项目：阿里巴巴日常实习生\n\n在这里，你将有机会：\n- 主导 AI Agent 的设计与优化——围绕大模型构建多 Agent 协作、任务规划、工具调用（Function Calling / MCP）、记忆与上下文管理等核心链路，持续提升 Agent 的准确率、稳定性与执行效率。\n- 参与构建 Agent 工程化体系，打造可复用的编排框架、评测基线、效果回归与可观测性能力，系统性优化 Agent 的端到端表现，推动智能化研发范式升级演进。\n- 深度参与国民级软件淘宝的 Agent 能力建设，与业务、算法、设计团队深度协作，把 Agent 能力转化为稳定可用的线上应用，推动产品快速迭代。\n- 面向 Agent 多轮推理成本、响应延迟、长链路稳定性、效果与成本平衡等业界前沿挑战，主导优化方案的设计与实施，提升淘宝用户的智能交互体验。\n- 与团队的专业小伙伴共同设计高效、高系统化、高鲁棒性的 Agent 架构，打造稳定、流畅的智能业务体验。\n\n加入我们，投身业内最前沿的 AI Agent 研发与优化。你将来自不同部门的优秀人才合作，既能获得专业指导与协作，也能在工作中不断挑战自我，在职业生涯中持续成长，享受 Agent 落地带来的乐趣和成就感。来吧，我们等你加入！\n\n【必备要求】\n- 本科及以上学历，计算机、软件、人工智能及电子信息等相关专业优先。\n- 工程基础扎实，学习能力强，对新事物抱有好奇心，并能快速适应新环境；具备良好的沟通、团队协同能力。\n- 熟悉主流的编程思想、数据结构和算法；至少精通一门主流语言（Python/Node.js/TypeScript 等），具备扎实的工程实现能力。\n- 熟悉 AI Agent 研发的核心场景，以下至少一项：熟悉主流 LLM 集成与应用范式、掌握 Prompt 工程化、有 Agent 编排/任务规划/工具调用（Function Calling / MCP）开发经验、熟悉 RAG 检索增强、熟悉 Agent 记忆与上下文管理。\n- 熟练掌握以下 Agent 细分领域知识（至少一项）：多 Agent 协作、Agent 效果评测与回归、推理链路优化（成本/延迟）、Agent 可观测性、AI 安全与可信、智能编码 Copilot。\n\n【加分项】\n- 有 AI Agent 落地项目经验，参与过 Agent 产品的技术方案设计，如智能编码助手、自动化运维 Agent、智能客服 Agent 等。\n- 熟悉 Agent 评测体系建设，能设计自动化评测基线与效果回归方案，量化驱动 Agent 优化。\n- 熟悉 AI 工程化基础设施，对 Prompt 管理、可观测性、模型推理加速、Rust 等高性能工具链有相关开发经验。",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "2026-06-24 阿里校招官网截图，毕业起止含 2025 较宽泛",
            "quality": 42,
            "quality_reason": "5 大方向 + 5 项必备要求 + 3 项加分项，字段完整",
            "authenticity": 22,
            "authenticity_reason": "用户从阿里校招官网截图手抄",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-T011",
        "company": "腾讯",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "腾讯 产品经理（技术背景）",
        "salary_range": "未披露",
        "location": "未披露",
        "source_url": "user_provided:腾讯校园招聘2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：腾讯\n招聘项目：腾讯校园招聘（日常实习）\n岗位标签：产品 / 日常实习\n\n岗位描述：\n1. 负责 toB（或 toG）平台产品的产品策划和运营工作，提供具有竞争力的产品方案，实现产品增长、商业化目标；\n2. 关注行业生态、同类产品动向，结合产品优势制定行业合作和市场运营方案，提升行业影响力；\n3. 持续关注云计算发展趋势，基于业界标杆和技术原理的分析，落地技术产品；\n4. 构建业务数据监控体系、IT 支持及客服体系、渠道和营销体系，持续改善系统架构、运营效率和成本，提升销售转化效率；\n5. 进行业务调研和客户反馈收集，提炼通用需求并判断优先级，推进销售或客户的痛点问题持续解决。\n\n岗位要求：\n1. 计算机、软件、人工智能、大数据等相关专业；\n2. 热爱互联网、热爱技术；对产品策划有激情，热爱思考，具有优秀的逻辑思维和创新能力；\n3. 有亲和力，擅于沟通，并有优秀的执行能力来保障需求的落地；\n4. 有服务意识，用心满足客户诉求，愿意深入了解客户的应用场景；\n5. 善于面对挑战和质疑。\n\n加分项或注意事项：\n- 有一定的编程能力者。",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "腾讯校园招聘官网 2026 当季实习",
            "quality": 36,
            "quality_reason": "岗位职责 5 项 + 岗位要求 5 项 + 加分项 1 项",
            "authenticity": 22,
            "authenticity_reason": "用户从腾讯校园招聘官网截图手抄",
            "total": 84,
            "grade": "A",
        },
    },
    {
        "id": "JD-T012",
        "company": "腾讯",
        "role_category": "general",
        "job_type": "ai_eng",
        "title": "腾讯 软件开发-全栈开发方向",
        "salary_range": "未披露",
        "location": "远程面试",
        "source_url": "user_provided:腾讯校园招聘2026-06-27截图",
        "source_quality": "unverified",
        "full_text": "公司：腾讯\n招聘项目：腾讯校园招聘（日常实习）\n岗位标签：技术 / 日常实习\n\n岗位描述：\n全栈开发工程师负责实现和优化公司的 IT 产品的技术架构建设，以及构建和维护关键 IT 服务与 IT 基础设施。\n\n1. 负责公司内部 IT 系统和对外业务管理系统的基础架构设计、方案规划和系统开发，包括但不限于：内部 IT 建设、企业核心管理领域、内部办公、研发过程管理、业务后台管理系统等；\n2. 通过对专业领域的理解和规划，结合自身的 IT 能力，提供业务与技术结合的全方案，解决专业领域 IT 化和落地实施的问题。\n\n岗位要求：\n1. 熟练掌握 React/Vue 等前端技术；\n2. 熟悉 Java/C++/Python/Go 等主流编程语言，接触过相应的框架并有一定的理解；\n3. 能熟练使用 MySQL/MongoDB 等数据库；\n4. 有较强的学习能力、分析及解决问题能力，具备良好的团队合作意识，心态好，有责任心。\n\n加分项或注意事项：\n1. 有 jQuery、node.js 等 js 框架使用及扩展编写经验；\n2. 了解 redis/memcache 等缓存中间件；\n3. 有性能优化方面的经验者。\n\n参加面试的城市：远程面试",
        "scores": {
            "timeliness": 26,
            "timeliness_reason": "腾讯校园招聘官网 2026 当季实习",
            "quality": 34,
            "quality_reason": "职责 2 项 + 要求 4 项 + 加分 3 项",
            "authenticity": 22,
            "authenticity_reason": "用户从腾讯校园招聘官网截图手抄",
            "total": 82,
            "grade": "A",
        },
    },
    {
        "id": "JD-B017",
        "company": "字节跳动",
        "role_category": "test_qa",
        "job_type": "ai_test",
        "title": "字节跳动 大模型测试开发实习生-抖音研发",
        "salary_range": "未披露",
        "location": "深圳",
        "source_url": "user_provided:字节跳动校招官网2026-06-27截图（职位ID: A63006）",
        "source_quality": "unverified",
        "full_text": "公司：字节跳动\n岗位：大模型测试开发实习生-抖音研发\n工作地点：深圳\n岗位类型：实习 / 研发-测试 / 日常实习\n职位 ID：A63006\n\n日常实习：面向全体在校生，为符合岗位要求的同学提供为期 3 个月及以上的项目实践机会。\n团队介绍：抖音研发部门负责多款大型产品的研发，包括但不限于抖音、西瓜视频、汽水音乐。\n\n加入我们，你将有机会参与亿级用户场景的开发与架构工作，使用前沿的技术助力业务一起不断成长。\n\n岗位职责：\n1. 深度参与大模型在质量保障方向的落地，解决当前大模型在落地过程中存在的各种问题；\n2. 基于大语言模型（LLM）构建高效、可靠的 Agent 核心引擎，实现全流程智能化测试开发；\n3. 通过对使用结果的数据深入分析，不断提升模型效果，提高使用体验；\n4. 深入测试流程的需求和痛点，不断挖掘、改进模型及工具，提升质效；\n5. 跟踪 Agent 领域前沿技术（如 ReAct、AutoGPT、CrewAI 等），推动技术落地与产品化。\n\n岗位要求：\n1. 本科及以上学历在读，计算机、软件工程等相关专业优先；\n2. 对大模型和算法方向有浓厚兴趣，熟悉至少一种 AI 应用开发框架（如 LangChain 等），熟悉 Prompt 工程、RAG、智能体（Agent）等理论；\n3. 具备优秀的业务理解能力，出色的问题分解与解决能力，能将模糊需求转化成实际应用落地，逻辑思维灵活全面，良好的沟通协作能力；\n4. 有扎实的计算机理论基础和代码编写能力，掌握至少一门编程语言，包括但不限于：Java/C/C++/Python/Go；\n5. 能保证至少 4 个月及以上的实习，每周可出勤至少 4 天及以上。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "字节跳动校招官网 2026 当季实习，附职位 ID A63006",
            "quality": 40,
            "quality_reason": "岗位职责 5 项 + 岗位要求 5 项，字段完整",
            "authenticity": 22,
            "authenticity_reason": "用户从字节跳动校招官网截图手抄，含职位 ID A63006",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-B018",
        "company": "字节跳动",
        "role_category": "general",
        "job_type": "ai_eng",
        "title": "字节跳动 前端开发实习生-剪映",
        "salary_range": "未披露",
        "location": "深圳",
        "source_url": "user_provided:字节跳动校招官网2026-06-27截图（职位ID: A153709A）",
        "source_quality": "unverified",
        "full_text": "公司：字节跳动\n岗位：前端开发实习生-剪映\n工作地点：深圳\n岗位类型：实习 / 研发-前端 / 日常实习\n职位 ID：A153709A\n\n日常实习：面向全体在校生，为符合岗位要求的同学提供为期 3 个月及以上的项目实践机会。\n团队介绍：字节跳动剪映研发团队，主要支持剪映、醒图、Faceu 等多款国内外产品的研发工作，业务覆盖多元化影像创作场景，截止 2021 年 6 月，相关产品多次登顶国内外 App Store 免费应用榜第一，并继续保持高速增长。加入我们，一起打造全球最受用户欢迎的影像创作产品。\n\n岗位职责：\n1. 参与剪映 CapCut 业务的平台开发，包括但不限于业务增长、内容、作者、商业化等平台业务；\n2. 参与具体解决方案的需求方案设计、项目推进工作；\n3. 参与技术架构升级、工具链、组件库建设，提升开发效率，优化关键卡点问题；\n4. 参与 AIGC 相关能力的业务开发，对于业务的效果敏感，针对业务痛点做基础能力相关的改进。\n\n岗位要求：\n1. 本科及以上学历在读，计算机、软件工程等相关专业优先；\n2. 热爱计算机科学和互联网技术，精通至少一门编程语言，包括但不仅限于：C/C++、Python、Go、Java、Typescript、JavaScript；\n3. 掌握扎实的计算机基础知识，深入理解数据结构、算法和操作系统知识；\n4. 有优秀的逻辑分析能力，能够对业务逻辑进行合理的抽象和拆分；\n5. 有强烈的求知欲，优秀的学习和沟通能力；\n6. 每周出勤至少 4 天，实习 3 个月及以上。\n\n加分项：\n1. 对 AI 兴趣浓厚，前端领域之外扩展学习 AI 相关知识，熟练掌握 AI 工具提升编程效率；\n2. 有全栈经验或者对全栈感兴趣优先。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "字节跳动校招官网 2026 当季实习，附职位 ID A153709A",
            "quality": 40,
            "quality_reason": "岗位职责 4 项 + 岗位要求 6 项 + 加分项 2 项",
            "authenticity": 22,
            "authenticity_reason": "用户从字节跳动校招官网截图手抄，含职位 ID A153709A",
            "total": 90,
            "grade": "A",
        },
    },
    {
        "id": "JD-B019",
        "company": "字节跳动",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "字节跳动 抖音小游戏产品实习生-抖音游戏",
        "salary_range": "未披露",
        "location": "深圳",
        "source_url": "user_provided:字节跳动校招官网2026-06-27截图（职位ID: A157670A）",
        "source_quality": "unverified",
        "full_text": "公司：字节跳动\n岗位：抖音小游戏产品实习生-抖音游戏\n工作地点：深圳\n岗位类型：实习 / 产品-产品经理 / 日常实习\n职位 ID：A157670A\n\n日常实习：面向全体在校生，为符合岗位要求的同学提供为期 3 个月及以上的项目实践机会。\n团队介绍：抖音游戏以\"激发游戏生命力\"为行业态度，致力于成为游戏综合平台，提供丰富、多元、全方位的游戏内容和服务，实现内容生产->消费->经营的正循环，让更多好玩的游戏涌现，让玩家发现更多乐趣。\n\n岗位职责：\n1. 协助支持抖音小游戏用户体验相关工作，围绕小游戏在 Feed、短视频、直播等流量场景中的体验链路，参与需求梳理、问题分析与方案推进；\n2. 参与用户体验研究与产品优化，关注用户在内容触达、点击、进入、游玩、转化等环节的体验表现，协助挖掘影响体验的关键问题并推动改进；\n3. 关注游戏行业与用户体验相关趋势，参与探索 AI 工具在体验优化、内容理解、用户洞察等方向的应用机会。\n\n岗位要求：\n1. 本科及以上学历在读，计算机相关专业优先；\n2. 有产品实习经验优先，具备基础的逻辑分析与问题拆解能力，能够从用户视角理解问题，并形成清晰的结论与建议；\n3. 对数据有一定敏感度，能够协助进行基础数据整理、体验分析和用户反馈归纳；\n4. 可连续实习 3 个月以上优先。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "字节跳动校招官网 2026 当季实习，附职位 ID A157670A",
            "quality": 34,
            "quality_reason": "岗位职责 3 项 + 岗位要求 4 项",
            "authenticity": 22,
            "authenticity_reason": "用户从字节跳动校招官网截图手抄，含职位 ID A157670A",
            "total": 84,
            "grade": "A",
        },
    },
    {
        "id": "JD-B020",
        "company": "字节跳动",
        "role_category": "product",
        "job_type": "ai_pm",
        "title": "字节跳动 AI 产品实习生（AI 分身）-抖音社交与互动",
        "salary_range": "未披露",
        "location": "深圳",
        "source_url": "user_provided:字节跳动校招官网2026-06-27截图（职位ID: A163711）",
        "source_quality": "unverified",
        "full_text": "公司：字节跳动\n岗位：AI 产品实习生（AI 分身）-抖音社交与互动\n工作地点：深圳\n岗位类型：实习 / 产品-产品经理 / 日常实习\n职位 ID：A163711\n\n日常实习：面向全体在校生，为符合岗位要求的同学提供为期 3 个月及以上的项目实践机会。\n团队介绍：抖音社交与互动团队服务于抖音连接人与人的愿景，希望为用户提供更好的社交、创作体验，以拓宽抖音的使用场景，成为更多人打开和使用抖音的新理由，提升抖音的用户规模。\n我们是一支有朝气、背景多元的团队，致力于为用户提供最佳的产品体验，热衷听取用户声音和反馈，也运用科学严谨的分析方法，仔细衡量我们的工作成果。抖音社交与互动欢迎你的加入，和我们一起做有挑战的事情。\n\n岗位职责：\n1. 参与抖音 AI 虚拟互动容器及 AI 分身作者端产品设计和规划，探索 AI 分身链接抖音用户社交的长期价值；\n2. 协同算法优化对话体验（多模态融合、角色化 LLM 等），提升用户互动；\n3. 探索社交场景下 AI 互动玩法（如 AI 互动作品，AI 交友等），设计落地方案；\n4. 同研发、数据分析、设计、运营等团队合作，高效推进项目落地。\n\n岗位要求：\n1. 本科及以上学历在读，AI/计算机等相关专业优先；\n2. 具备用户理解、数据分析及跨团队协作能力，逻辑清晰，能快速定位问题；\n3. 对 AI 技术（LLM、对话系统）有兴趣，了解大模型基础原理者优先；熟悉社交产品或有内容创作经验者优先；\n4. 每周 4-5 天到岗，实习期至少 3 个月，长期优先。",
        "scores": {
            "timeliness": 28,
            "timeliness_reason": "字节跳动校招官网 2026 当季实习，附职位 ID A163711",
            "quality": 36,
            "quality_reason": "岗位职责 4 项 + 岗位要求 4 项",
            "authenticity": 22,
            "authenticity_reason": "用户从字节跳动校招官网截图手抄，含职位 ID A163711",
            "total": 86,
            "grade": "A",
        },
    },
]


def main():
    # 读 v3
    data = json.loads(SRC.read_text(encoding="utf-8"))
    v3_jds = data["jds"]

    # 去重: 排除已存在的 id
    existing_ids = {jd["id"] for jd in v3_jds}
    new_jds = [jd for jd in NEW_JDS if jd["id"] not in existing_ids]

    # 合并
    all_jds = v3_jds + new_jds

    # 更新 meta
    data["jds"] = all_jds
    data["_meta"]["version"] = "4.0.0-intern"
    data["_meta"]["generated_at"] = "2026-06-26"
    data["_meta"]["filter_dimension"] = "实习岗匹配度（v4 补搜版）"
    data["_meta"]["v4_addon"] = {
        "added_count": len(new_jds),
        "total_count": len(all_jds),
        "search_strategy": [
            "关键词组合 1: 大模型算法 + 实习 + 招聘",
            "关键词组合 2: AI 产品经理 + 实习生 + nowcoder/boss",
            "关键词组合 3: 算法实习生 + 大模型/深度学习",
            "关键词组合 4: DeepSeek/阿里通义/字节 AI + 实习生 + 2026",
            "关键词组合 5: 大模型数据 + 实习生 + 数据标注",
            "关键词组合 6: 蚂蚁/京东/美团 + 大模型算法 + 实习生",
        ],
        "added_companies": sorted({jd["company"] for jd in new_jds}),
    }

    # 写 v4
    DST.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[OK] {DST} ({DST.stat().st_size} bytes)")
    print(f"[Stats] v3: {len(v3_jds)} → v4: {len(all_jds)} (新增 {len(new_jds)})")
    print(f"[Stats] 新增覆盖公司: {', '.join(sorted({jd['company'] for jd in new_jds}))}")


if __name__ == "__main__":
    main()